name: Publish extension

on:
  workflow_dispatch:

jobs:
  publish_extension:
    name: Publish extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db
        with:
          pat: ${{ secrets.VSCODE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
